spring:
  application:
    name: Qflow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/qflow}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  main:
    banner-mode: console
jwt:
  secret: ${JWT_SECRET:mysecretkey}